-- AlterTable
ALTER TABLE "Notification" ALTER COLUMN "Bylat" DROP DEFAULT,
ALTER COLUMN "Bylng" DROP DEFAULT,
ALTER COLUMN "Tolat" DROP DEFAULT,
ALTER COLUMN "Tolng" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "lat" DROP DEFAULT,
ALTER COLUMN "lng" DROP DEFAULT;
